// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzKGcrlyj3BzDA0X_ooNqZ7F3t_uFVGYM',
    appId: '1:1025583525806:web:39b0ef4bc572711ce6623f',
    messagingSenderId: '1025583525806',
    projectId: 'loginabsen-7a53d',
    authDomain: 'loginabsen-7a53d.firebaseapp.com',
    storageBucket: 'loginabsen-7a53d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCM5OkAIG0Gr9o1QIcckUTw0Nqfo2pgx8',
    appId: '1:1025583525806:android:3e5be081da2ef992e6623f',
    messagingSenderId: '1025583525806',
    projectId: 'loginabsen-7a53d',
    storageBucket: 'loginabsen-7a53d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRKByQGqAbHYKmAg5AzDsCcPYCUJPWFO4',
    appId: '1:1025583525806:ios:05a99ce1dde61225e6623f',
    messagingSenderId: '1025583525806',
    projectId: 'loginabsen-7a53d',
    storageBucket: 'loginabsen-7a53d.appspot.com',
    iosBundleId: 'com.example.loginPageDone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRKByQGqAbHYKmAg5AzDsCcPYCUJPWFO4',
    appId: '1:1025583525806:ios:4ec903fedb55afe0e6623f',
    messagingSenderId: '1025583525806',
    projectId: 'loginabsen-7a53d',
    storageBucket: 'loginabsen-7a53d.appspot.com',
    iosBundleId: 'com.example.loginPageDone.RunnerTests',
  );
}
